sudo: false
language: node_js
node_js: stable
cache: npm
branches:
  only:
    - Source
before_install:
  - git submodule update --init --remote --recursive

install:
  - npm install
script:
  - npm run build # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GitHub_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public
