# ===========================================
# Site Settings
# ===========================================
# Header
site_title: Troy's Blog
site_description: Focus on Web Development and live in ChengDu. Happy Coding, Happy Life!
menu:
  Home: /
  Archives: /archives
  AboutMe: /about
# display widgets
widgets:
- archives
- recent_posts
- tagcloud
# widget behavior
archive_type: 'monthly'
show_count: true
# Content
excerpt_link: Read More
# favico 
favicon:

# ===========================================
# Miscellaneous Settings
# ===========================================
# Baidu Analytics
baidu_analytics: 542b4962c3c4035fce9071b7c665f0d2
# Google Analytics
google_analytics: UA-97838175-1
# Disqus
disqus:
  enable: false
  shortname: troyyang-com
  count: true
# changyan
changyan:
  enable: false
  appid:
  appkey:
# duoshuo
duoshuo:
  enable: true
  shortname: troyyang